language: python
git:
  depth: 3
python:
- '3.7'
install:
- pip install pipenv coveralls pylint pytest pytest-cov
script:
- pytest --cov=imdb/
- pylint imdb --exit-zero
after_success:
- coveralls
deploy:
  provider: pypi
  user: __token__
  password:
    secure: s7nbmdgGPSTVePeKkHL7NzFoxFBdX3pmhxIS95ESlw2Kc1S/30NVXNSOGwszl3H+ixYsPMPX8zay+tSHLYopBSPaDbETI1/10puiqk8Xf13CwqgzqZ7pFnvsIs8t3YM1nMSD8L0yyp3k96jwpd9UzPKeE96scEWV53VqI54VjM0dkunkEDIwmj1lJr0v3FLClyal4oLfZmI7O5InIsgXCwUG5U2Ybuj3SSR5Q2aJfr18Cs1woyN7CPxQGsfB0BtaYZ4d6IZVfu6I2kztCPBXR5Y4fOFb0XDk3fRQN1S7uHX3CuzS0XF+r6tedAsirpgI6h0IMOzvEYCXkcx1zagbz/BMnE0+tB9S4t325UAG9eBDqxkyV1/N0i53nlNfIpYP5tm+cs/lpPPKebf9z5ZKv2ZexA/xuRkogaW963LbkwA6rYDsn6NPmUA92dntbKMMqi2kFaApLtdoR5SNQxYG3YSI44G7oMYyrGBLVSGLrjffVKXy83NQ8hOT0A/AHXbzSiUFVuoCH6qFgrwdb3FmiOYkkkY326RvcP1SxHzDx48P0M6rCQt8fqKAZpnSdZoAXgtE5XxRgkb9lsFetKfuy3gojumnb0qGdWjiXJ+PZQgATiNofq6BRD5MVtK4wOtOAospK/ZbTOVYXZwfOflx9apztyejSrqzHSuYN4q+U+g=
  server: https://test.pypi.org/legacy/
  on:
    tags: true
notifications:
  irc: chat.freenode.net#bardiharborow
